export const resetToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjcyMjAwNjUwLCJleHAiOjE2NzIyMDI0NTAsImF1ZCI6InVzZXJzIiwiaXNzIjoiZm9yZ2V0Iiwic3ViIjoiMSJ9.mZZF2D3s_06eskyfFOJOWxb5fZkLe_GN2RRmbviHmJI';
